package com.example.personeltracking2026kodau.utils

import android.content.Context
import android.provider.Settings

class DeviceIdentityManager(private val context: Context) {

    private val prefs = context.getSharedPreferences(PREF_NAME, Context.MODE_PRIVATE)

    data class DeviceIdentity(
        val serial      : String,
        val androidId   : String
    )
    companion object {
        private const val PREF_NAME = "device_identity_prefs"
        private const val KEY_SERIAL = "serial_number"
        private const val KEY_DEVICE_ID = "device_id"
        private const val KEY_IS_AUTO = "is_auto_generated"
    }

    // Ambil Android ID (unik per device)
    private fun getCurrentDeviceId(): String {
        return Settings.Secure.getString(
            context.contentResolver,
            Settings.Secure.ANDROID_ID
        )
    }

    // Simpan serial (hanya kalau belum pernah diset)
    fun saveSerialIfEmpty(serial: String): Boolean {
        val existing = prefs.getString(KEY_SERIAL, null)
        if (existing != null) return false

        val deviceId = getCurrentDeviceId()

        prefs.edit()
            .putString(KEY_SERIAL, serial)
            .putString(KEY_DEVICE_ID, deviceId)
            .apply()

        return true
    }

    // Force update (kalau mau ada fitur reset/admin)
    fun forceUpdateSerial(serial: String) {
        val deviceId = getCurrentDeviceId()

        prefs.edit()
            .putString(KEY_SERIAL, serial)
            .putString(KEY_DEVICE_ID, deviceId)
            .putBoolean(KEY_IS_AUTO, false)
            .apply()
    }

    // Ambil serial yang valid (cek device ID)
    fun getValidSerial(): String? {
        val savedSerial = prefs.getString(KEY_SERIAL, null)
        val savedDeviceId = prefs.getString(KEY_DEVICE_ID, null)

        val currentDeviceId = getCurrentDeviceId()

        return if (savedSerial != null && savedDeviceId == currentDeviceId) {
            savedSerial
        } else {
            null
        }
    }

    // Cek apakah serial sudah ada
    fun isSerialExists(): Boolean {
        return getValidSerial() != null
    }

    // Optional: clear data (misal logout / reset device)
    fun clear() {
        prefs.edit().clear().apply()
    }

    fun getIdentity(): DeviceIdentity {
        val existingSerial = getValidSerial()

        if (existingSerial != null) {
            return DeviceIdentity(
                serial = existingSerial,
                androidId = existingSerial
            )
        }

        val androidId = getCurrentDeviceId()
        val serial = "ANDROID_$androidId"

        prefs.edit()
            .putString(KEY_SERIAL, serial)
            .putString(KEY_DEVICE_ID, androidId)
            .putBoolean(KEY_IS_AUTO, true)
            .apply()

        return DeviceIdentity(serial, serial)
    }

    fun isAutoGenerated(): Boolean {
        return prefs.getBoolean(KEY_IS_AUTO, false)
    }
}
