package com.example.personeltracking2026kodau.ui.bluetooth

import android.bluetooth.BluetoothAdapter
import android.bluetooth.le.BluetoothLeScanner
import android.bluetooth.le.ScanCallback
import android.bluetooth.le.ScanResult
import android.content.ComponentName
import android.content.Context
import android.content.Intent
import android.content.ServiceConnection
import android.content.pm.PackageManager
import android.os.Build
import android.os.Bundle
import android.os.Handler
import android.os.IBinder
import android.os.Looper
import android.util.Log
import android.view.View
import android.widget.*
import androidx.activity.result.contract.ActivityResultContracts
import androidx.appcompat.app.AlertDialog
import androidx.appcompat.widget.SwitchCompat
import androidx.core.content.ContextCompat
import androidx.lifecycle.lifecycleScope
import com.example.personeltracking2026kodau.App
import com.example.personeltracking2026kodau.R
import com.example.personeltracking2026kodau.core.base.BaseActivity
import com.example.personeltracking2026kodau.core.session.SessionManager
import com.example.personeltracking2026kodau.core.sos.SosManager
import com.example.personeltracking2026kodau.ui.settings.SettingsActivity
import com.example.personeltracking2026kodau.utils.DeviceIdentityManager
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch

class BluetoothActivity : BaseActivity() {

    // ── Views ─────────────────────────────────────────────────────────────
    private lateinit var switchBluetooth: SwitchCompat
    private lateinit var tvToggleLabel: TextView
    private lateinit var btnBack: ImageButton
    private lateinit var btnRefresh: ImageButton
    private lateinit var layoutBluetoothOff: LinearLayout
    private lateinit var layoutScanning: LinearLayout
    private lateinit var layoutConnectedInfo: LinearLayout
    private lateinit var layoutDeviceList: LinearLayout
    private lateinit var tvDeviceCount: TextView
    private lateinit var tvScanStatus: TextView
    private lateinit var bluetoothScanView: BluetoothScanView
    private lateinit var tvConnectedName: TextView
    private lateinit var tvConnectedMac: TextView
    private lateinit var tvBpm: TextView
    private lateinit var tvHeartStatus: TextView

    // ── Bluetooth ─────────────────────────────────────────────────────────
    private val bluetoothAdapter: BluetoothAdapter? = BluetoothAdapter.getDefaultAdapter()
    private var bluetoothLeScanner: BluetoothLeScanner? = null
    private var isScanning = false

    // ── Service ───────────────────────────────────────────────────────────
    private var bleService: BluetoothLeService? = null
    private var isBound = false

    private val serviceConnection = object : ServiceConnection {
        override fun onServiceConnected(name: ComponentName?, service: IBinder?) {
            val binder = service as BluetoothLeService.LocalBinder
            bleService = binder.getService()
            isBound = true
            observeService()
            syncUIWithService()
        }
        override fun onServiceDisconnected(name: ComponentName?) {
            isBound = false
            bleService = null
        }
    }

    // ── Data ─────────────────────────────────────────────────────────────
    private val deviceList = mutableListOf<BluetoothDeviceModel>()
    private lateinit var adapter: BluetoothDeviceAdapter
    private val mainHandler = Handler(Looper.getMainLooper())
    private var hasRequestedInitialPermission = false

    // ══════════════════════════════════════════════════════════════════════
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_bluetooth)

        val deviceManager = DeviceIdentityManager(this)
        val identity = deviceManager.getIdentity()

        if (deviceManager.isAutoGenerated()) {
            showSerialDialog()
        }

        val app = application as App
        SosManager.init(
            mqtt             = app.mqttManager,
            session          = SessionManager(this),
            serial           = identity.serial,
            id               = identity.androidId,
            type             = SosManager.DeviceType.RADIO,
            locationProvider = { Triple(app.currentLat, app.currentLon, app.currentAccuracy) } // atau bisa diganti kalau ada location
        )

        initViews()
        setupAdapter()
        setupListeners()

        if (hasPermission()) {
            ensureServiceBound()
        } else {
            showPermissionRequiredState()
            requestPermissions()
            hasRequestedInitialPermission = true
        }
    }

    override fun onDestroy() {
        super.onDestroy()
        stopScan()
        mainHandler.removeCallbacksAndMessages(null)
        if (isBound) {
            unbindService(serviceConnection)
            isBound = false
        }
        // JANGAN stop service — biarkan koneksi tetap hidup
    }

    // ══════════════════════════════════════════════════════════════════════
    // INIT
    // ══════════════════════════════════════════════════════════════════════

    private fun initViews() {
        switchBluetooth     = findViewById(R.id.switchBluetooth)
        tvToggleLabel       = findViewById(R.id.tvToggleLabel)
        btnBack             = findViewById(R.id.btnBack)
        btnRefresh          = findViewById(R.id.btnRefresh)
        layoutBluetoothOff  = findViewById(R.id.layoutBluetoothOff)
        layoutScanning      = findViewById(R.id.layoutScanning)
        layoutConnectedInfo = findViewById(R.id.layoutConnectedInfo)
        layoutDeviceList    = findViewById(R.id.layoutDeviceList)
        tvDeviceCount       = findViewById(R.id.tvDeviceCount)
        tvScanStatus        = findViewById(R.id.tvScanStatus)
        bluetoothScanView   = findViewById(R.id.bluetoothScanView)
        tvConnectedName     = findViewById(R.id.tvConnectedName)
        tvConnectedMac      = findViewById(R.id.tvConnectedMac)
        tvBpm               = findViewById(R.id.tvBpm)
        tvHeartStatus       = findViewById(R.id.tvHeartStatus)
    }

    private fun setupAdapter() {
        adapter = BluetoothDeviceAdapter(
            context      = this,
            onConnect    = { device -> connectToDevice(device) },
            onDisconnect = { _ ->
                if (hasPermission()) {
                    bleService?.disconnect()
                } else {
                    requestPermissions()
                }
            }
        )
    }

    private fun ensureServiceBound() {
        if (isBound) {
            syncUIWithService()
            return
        }

        val serviceIntent = Intent(this, BluetoothLeService::class.java)
        ContextCompat.startForegroundService(this, serviceIntent)
        bindService(serviceIntent, serviceConnection, Context.BIND_AUTO_CREATE)
    }

    // ══════════════════════════════════════════════════════════════════════
    // OBSERVE SERVICE
    // ══════════════════════════════════════════════════════════════════════

    private fun observeService() {
        lifecycleScope.launch {
            BluetoothLeService.connectionState.collect { state ->
                when (state) {
                    BluetoothLeService.ConnectionState.CONNECTED -> {
                        val device = BluetoothLeService.connectedDevice.value
                        if (device != null) showConnectedInfo(device)
                        updateDeviceStatesFromService()
                        updateDeviceList()
                    }
                    BluetoothLeService.ConnectionState.CONNECTING -> {
                        updateDeviceStatesFromService()
                        updateDeviceList()
                    }
                    BluetoothLeService.ConnectionState.DISCONNECTED -> {
                        hideConnectedInfo()
                        updateDeviceStatesFromService()
                        updateDeviceList()
                    }
                }
            }
        }

        lifecycleScope.launch {
            val app = application as App
            app.effectiveHeartRate.collect { bpm ->
                updateBpm(bpm)
            }
        }
    }

    private fun syncUIWithService() {
        if (!hasPermission()) {
            showPermissionRequiredState()
            if (!hasRequestedInitialPermission) {
                requestPermissions()
                hasRequestedInitialPermission = true
            }
            return
        }

        val isBluetoothOn = bluetoothAdapter?.isEnabled == true
        switchBluetooth.setOnCheckedChangeListener(null)
        switchBluetooth.isChecked = isBluetoothOn
        setupSwitchListener()
        updateToggleUI(isBluetoothOn)

        when {
            !isBluetoothOn -> showOffState()
            BluetoothLeService.connectionState.value == BluetoothLeService.ConnectionState.CONNECTED -> {
                showScanningLayout()
                val device = BluetoothLeService.connectedDevice.value
                if (device != null) {
                    if (deviceList.none { it.address == device.address }) {
                        deviceList.add(device.copy(state = DeviceState.CONNECTED))
                    } else {
                        deviceList.find { it.address == device.address }?.state = DeviceState.CONNECTED
                    }
                    showConnectedInfo(device)
                    updateDeviceList()
                }
                tvScanStatus.text = "Device connected"
                tvDeviceCount.visibility = View.VISIBLE
                tvDeviceCount.text = "${deviceList.size} Device found"
                // Sudah connected — tidak perlu scan ulang
                bluetoothScanView.stopAnimation()
            }
            else -> {
                showScanningLayout()
                startScan()
            }
        }
    }

    // ══════════════════════════════════════════════════════════════════════
    // LISTENERS
    // ══════════════════════════════════════════════════════════════════════

    private fun setupListeners() {
        btnBack.setOnClickListener { finish() }
        btnRefresh.setOnClickListener {
            if (hasPermission()) {
                stopScan()
                deviceList.clear()
                updateDeviceList()
                startScan()
            } else {
                requestPermissions()
            }
        }
        setupSwitchListener()
    }

    private fun setupSwitchListener() {
        switchBluetooth.setOnCheckedChangeListener { _, isChecked ->
            if (!hasPermission()) {
                requestPermissions()
                switchBluetooth.setOnCheckedChangeListener(null)
                switchBluetooth.isChecked = !isChecked
                setupSwitchListener()
                return@setOnCheckedChangeListener
            }

            if (isChecked) {
                // Android 10+ tidak bisa enable() langsung — pakai Intent
                val enableBtIntent = Intent(BluetoothAdapter.ACTION_REQUEST_ENABLE)
                enableBluetoothLauncher.launch(enableBtIntent)
            } else {
                // Putuskan koneksi BLE
                bleService?.disconnect()
                stopScan()
                deviceList.clear()
                showOffState()
                updateToggleUI(false)
                Toast.makeText(
                    this,
                    "Please use system settings to disable Bluetooth",
                    Toast.LENGTH_SHORT
                ).show()
            }
        }
    }

    // ══════════════════════════════════════════════════════════════════════
    // UI STATE
    // ══════════════════════════════════════════════════════════════════════

    private fun showOffState() {
        layoutBluetoothOff.visibility  = View.VISIBLE
        layoutScanning.visibility      = View.GONE
        layoutConnectedInfo.visibility = View.GONE
        layoutDeviceList.visibility    = View.GONE
        bluetoothScanView.stopAnimation()
    }

    private fun showPermissionRequiredState() {
        stopScan()
        deviceList.clear()
        updateDeviceList()
        switchBluetooth.setOnCheckedChangeListener(null)
        switchBluetooth.isChecked = false
        setupSwitchListener()
        updateToggleUI(false)
        layoutBluetoothOff.visibility = View.GONE
        layoutScanning.visibility = View.VISIBLE
        layoutConnectedInfo.visibility = View.GONE
        layoutDeviceList.visibility = View.GONE
        bluetoothScanView.stopAnimation()
        tvDeviceCount.visibility = View.GONE
        tvScanStatus.text = "Bluetooth permission required"
    }

    private fun showScanningLayout() {
        layoutBluetoothOff.visibility = View.GONE
        layoutScanning.visibility     = View.VISIBLE
        layoutDeviceList.visibility   = View.VISIBLE
        bluetoothScanView.startAnimation()
    }

    private fun updateToggleUI(isOn: Boolean) {
        if (isOn) {
            tvToggleLabel.text = "Active"
            tvToggleLabel.setTextColor(ContextCompat.getColor(this, R.color.primary))
        } else {
            tvToggleLabel.text = "Inactive"
            tvToggleLabel.setTextColor(ContextCompat.getColor(this, R.color.gray))
        }
    }

    private fun showConnectedInfo(device: BluetoothDeviceModel) {
        layoutConnectedInfo.visibility = View.VISIBLE
        tvConnectedName.text = device.name.ifBlank { "Unknown" }
        tvConnectedMac.text  = device.address
    }

    private fun hideConnectedInfo() {
        layoutConnectedInfo.visibility = View.GONE
        tvBpm.text = "--"
    }

    private fun updateBpm(bpm: Int) {
        tvBpm.text = bpm.toString()
        val (statusText, colorRes) = when {
            bpm == 0 -> "--" to R.color.gray
            bpm < 60  -> "Below normal" to R.color.orange
            bpm > 100 -> "Above normal"  to R.color.red
            else      -> "Normal"           to R.color.gray
        }
        tvHeartStatus.text = statusText
        tvHeartStatus.setTextColor(ContextCompat.getColor(this, colorRes))
    }

    private fun updateDeviceList() {
        val count = deviceList.size
        tvDeviceCount.visibility = if (count > 0) View.VISIBLE else View.GONE
        if (count > 0) tvDeviceCount.text = "$count Device found"
        adapter.renderInto(layoutDeviceList, deviceList)
    }

    private fun updateDeviceStatesFromService() {
        val connAddr = BluetoothLeService.connectedDevice.value?.address
        val svcState = BluetoothLeService.connectionState.value
        deviceList.forEach { d ->
            d.state = when {
                d.address == connAddr && svcState == BluetoothLeService.ConnectionState.CONNECTED  -> DeviceState.CONNECTED
                d.address == connAddr && svcState == BluetoothLeService.ConnectionState.CONNECTING -> DeviceState.CONNECTING
                else -> DeviceState.IDLE
            }
        }
    }

    // ══════════════════════════════════════════════════════════════════════
    // BLE SCAN
    // ══════════════════════════════════════════════════════════════════════

    private fun startScan() {
        if (!hasPermission()) {
            requestPermissions()
            return
        }

        if (bluetoothAdapter?.isEnabled != true) {
            showOffState()
            updateToggleUI(false)
            return
        }

        bluetoothLeScanner = bluetoothAdapter?.bluetoothLeScanner
        if (bluetoothLeScanner == null) {
            tvScanStatus.text = "Bluetooth scanner unavailable"
            return
        }

        isScanning = true
        tvScanStatus.text = "Searching for devices . . ."
        bluetoothScanView.startAnimation()

        try {
            bluetoothLeScanner?.startScan(scanCallback)
        } catch (e: SecurityException) {
            Log.e("BT", "startScan: ${e.message}")
        }

        mainHandler.postDelayed({
            if (isScanning) {
                stopScan()
                tvScanStatus.text = "Scan completed"
                bluetoothScanView.stopAnimation()
            }
        }, 30_000)
    }

    private fun stopScan() {
        if (!isScanning) return
        isScanning = false
        try {
            if (hasPermission()) bluetoothLeScanner?.stopScan(scanCallback)
        } catch (e: SecurityException) { }
    }

    private val scanCallback = object : ScanCallback() {
        override fun onScanResult(callbackType: Int, result: ScanResult) {
            val device = result.device ?: return
            val name = try {
                if (hasPermission()) device.name ?: return else return
            } catch (e: SecurityException) { return }

            val address = device.address
            if (deviceList.none { it.address == address }) {
                val model = BluetoothDeviceModel(name, address, result.rssi)
                if (address == BluetoothLeService.connectedDevice.value?.address) {
                    model.state = DeviceState.CONNECTED
                }
                deviceList.add(model)
                deviceList.sortByDescending { it.rssi }
                runOnUiThread { updateDeviceList() }
            }
        }

        override fun onScanFailed(errorCode: Int) {
            runOnUiThread { tvScanStatus.text = "Failed to search for devices ($errorCode)" }
        }
    }

    // ══════════════════════════════════════════════════════════════════════
    // CONNECT
    // ══════════════════════════════════════════════════════════════════════

    private fun connectToDevice(deviceModel: BluetoothDeviceModel) {
        val service = bleService
        if (service == null) {
            ensureServiceBound()
            Toast.makeText(this, "Bluetooth service sedang disiapkan", Toast.LENGTH_SHORT).show()
            return
        }

        if (!hasPermission()) {
            requestPermissions()
            return
        }

        val btAdapter = bluetoothAdapter ?: run {
            Toast.makeText(this, "Bluetooth tidak tersedia", Toast.LENGTH_SHORT).show()
            return
        }

        if (!btAdapter.isEnabled) {
            val enableBtIntent = Intent(BluetoothAdapter.ACTION_REQUEST_ENABLE)
            enableBluetoothLauncher.launch(enableBtIntent)
            return
        }

        val connectionState = BluetoothLeService.connectionState.value
        val connectedDevice = BluetoothLeService.connectedDevice.value

        if (
            connectedDevice?.address == deviceModel.address &&
            connectionState == BluetoothLeService.ConnectionState.CONNECTED
        ) {
            return
        }

        if (
            connectedDevice?.address == deviceModel.address &&
            connectionState == BluetoothLeService.ConnectionState.CONNECTING
        ) {
            return
        }

        stopScan()
        bluetoothScanView.stopAnimation()
        tvScanStatus.text = "Connecting to ${deviceModel.name.ifBlank { "device" }}..."

        deviceList.forEach { device ->
            device.state = if (device.address == deviceModel.address) {
                DeviceState.CONNECTING
            } else {
                DeviceState.IDLE
            }
        }
        updateDeviceList()

        lifecycleScope.launch {
            val shouldDisconnectFirst =
                connectionState != BluetoothLeService.ConnectionState.DISCONNECTED &&
                        connectedDevice?.address != deviceModel.address

            if (shouldDisconnectFirst) {
                service.disconnect()
                delay(500)
                deviceList.forEach { device ->
                    device.state = if (device.address == deviceModel.address) {
                        DeviceState.CONNECTING
                    } else {
                        DeviceState.IDLE
                    }
                }
                updateDeviceList()
            }

            service.connect(deviceModel.copy(state = DeviceState.CONNECTING), btAdapter)
        }
    }

    // ══════════════════════════════════════════════════════════════════════
    // PERMISSION
    // ══════════════════════════════════════════════════════════════════════

    private fun hasPermission(): Boolean {
        return requiredBluetoothPermissions().all { permission ->
            ContextCompat.checkSelfPermission(this, permission) == PackageManager.PERMISSION_GRANTED
        }
    }

    private fun requestPermissions() {
        requestPermissionLauncher.launch(requiredBluetoothPermissions())
    }

    private fun requiredBluetoothPermissions(): Array<String> {
        return if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
            arrayOf(
                android.Manifest.permission.BLUETOOTH_SCAN,
                android.Manifest.permission.BLUETOOTH_CONNECT
            )
        } else {
            arrayOf(android.Manifest.permission.ACCESS_FINE_LOCATION)
        }
    }

    private val enableBluetoothLauncher =
        registerForActivityResult(ActivityResultContracts.StartActivityForResult()) {
            val isOn = bluetoothAdapter?.isEnabled == true
            switchBluetooth.setOnCheckedChangeListener(null)
            switchBluetooth.isChecked = isOn
            setupSwitchListener()
            updateToggleUI(isOn)
            if (isOn) {
                showScanningLayout()
                startScan()
            }
        }

    private val requestPermissionLauncher =
        registerForActivityResult(ActivityResultContracts.RequestMultiplePermissions()) { results ->
            val granted = requiredBluetoothPermissions().all { permission ->
                results[permission] == true
            }
            if (granted) {
                ensureServiceBound()
            } else {
                showPermissionRequiredState()
                Toast.makeText(this, "Bluetooth permission required", Toast.LENGTH_SHORT).show()
            }
        }

    // ══════════════════════════════════════════════════════════════════════
    // SERIAL NUMBER DIALOG
    // ══════════════════════════════════════════════════════════════════════

    private fun showSerialDialog() {
        val dialogView = layoutInflater.inflate(R.layout.dialog_serial_req, null)

        val dialog = AlertDialog.Builder(this)
            .setView(dialogView)
            .setCancelable(false)
            .create()

        val btnLater = dialogView.findViewById<Button>(R.id.btnLater)
        val btnSetting = dialogView.findViewById<Button>(R.id.btnGoToSetting)

        btnLater.setOnClickListener {
            dialog.dismiss()
        }

        btnSetting.setOnClickListener {
            dialog.dismiss()
            startActivity(Intent(this, SettingsActivity::class.java))
        }
        dialog.show()

        dialog.window?.setBackgroundDrawableResource(android.R.color.transparent)
    }
}
